project:
  type: website
  output-dir: docs
  title: "robertwwalker.github.io"

website:
  title: "{{< fa brands r-project >}}obertwwalker.github.io"
  site-url: "https://robertwwalker.github.io"
  repo-url: "https://github.com/robertwwalker/robertwwalker.github.io"
  favicon: favicon.png
  twitter-card: 
    creator: "@PieRatio"
  page-navigation: true
  navbar:
    search: true
    logo: "AGSMlogo.jpeg"
    right:
      - text: Home
        icon: house
        file: index.qmd
      - file: about.qmd
        icon: question
        text: About
      - file: where.qmd
        icon: globe
        text: Where      
      - file: links.qmd
        icon: link
        text: Links      
      - text: Courses
        icon: mortarboard-fill
        menu:
            - text: Data Analysis, Modelling, and Decision-Making
              href: courses/courses-DADM.qmd
            - text: Communicating With Data
              href: courses/courses-CWD.qmd
            - text: Choice and Forecasting
              href: courses/courses-CAF.qmd
            - text: Panel Data
              href: courses/courses-Essex.qmd
      - text: Slides
        icon: mortarboard-fill
        menu:
            - text: DADM
              href: slides/slides-DADM.qmd
            - text: CWD
              href: slides/slides-CWD.qmd
            - text: Essex
              href: slides/slides-Essex.qmd
            - text: CMF
              href: slides/slides-CMF.qmd
      - icon: github
        href: https://github.com/robertwwalker
      - icon: twitter
        href: https://twitter.com/PieRatio

# This footer was inspired by Andrew Heiss's website
# I don't much care one way or the other about copyright here
# But the license requires attribution.
  page-footer:
    left: |
      <span class="faux-block">License: [{{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-sa >}} Creative Commons CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)</span>      
    right: |
      <span class="faux-block">{{< fa brands r-project >}} and [Quarto](https://quarto.org/)</span>
      <span class="faux-block">[View the source at {{< fa brands github >}} GitHub]({{< var github-url >}})</span>


format:
  html:
    theme: morph
    css: styles.css
    email-obfuscation: javascript
    code-fold: true
    code-summary: "How's that done?"




