---
title: Links
toc: true
toc-title: <br><br><br><br><br><br><br><br><br><br><br><br>Links Contents
toc-location: right
comments:
   giscus: 
     repo: robertwwalker/robertwwalker.github.io
---

```{r setup, include=FALSE}
library(distilltools)
```

<marquee scrollamount="10"><h1><p style="color:purple;">{{< fa brands r-project >}}obertwwalker.github.io <br></p></h1></marquee>

## Data

- [Our World in Data](https://ourworldindata.org)
- [Kaggle](https://www.kaggle.com)
- [#tidyTuesday](https://github.com/rfordatascience/tidytuesday)
- [Though dated, an amazing resource from kdnuggets](https://www.kdnuggets.com/2017/12/big-data-free-sources.html)
- [Harvard Dataverse](https://dataverse.harvard.edu)
- [World Bank Open Data](https://data.worldbank.org)
- [World Health Organization Open Data](https://www.who.int/gho/database/en/)
- [Google public data explorer](https://www.google.com/publicdata/directory)
- [Registry of Open Data on AWS](https://registry.opendata.aws)
- [fivethirtyeight](https://data.fivethirtyeight.com)
- [The US Census Bureau](https://www.census.gov/data.html)
- [data.gov](https://data.gov)
- [dbpedia](https://www.dbpedia.org)
- [inside airbnb](http://insideairbnb.com/get-the-data/)
- [yelp open data](https://www.yelp.com/dataset)
- [UNICEF data](https://data.unicef.org)



## R for Data Science

From the front page of the second edition website.

::: {.callout-tip}
This book will teach you how to do data science with R: You’ll learn how to get your data into R, get it into the most useful structure, transform it and visualize.
:::

`r icon_link(
  icon = "book",
  text = "R for Data Science (1st Edition)",
  url = "https://r4ds.had.co.nz/"
)`

`r icon_link(
  icon = "book",
  text = "R for Data Science (2nd Edition)",
  url = "https://r4ds.hadley.nz/"
)`

`r icon_link(
  icon = "twitter",
  text = "#r4ds",
  url = "https://twitter.com/hashtag/r4ds"
)`


## Twitter

The #rstats hashtag is the best place to start on Twitter.

`r icon_link(
  icon = "twitter",
  text = "#rstats",
  url = "https://twitter.com/hashtag/rstats"
)`

## Mastodon

R users are also on Mastodon, an open-source social network that is becoming increasingly popular.^[Danielle Navarro has an [excellent guide](https://blog.djnavarro.net/posts/2022-11-03_what-i-know-about-mastodon/){target="_blank"} for data science folks trying to navigate the fediverse.] The #rstats tag is most active on fosstodon.

`r icon_link(
  icon = "mastodon",
  text = "fosstodon",
  url = "https://fosstodon.org/"
)`

`r icon_link(
  icon = "mastodon",
  text = "mastodon.social",
  url = "https://mastodon.social/"
)`

`r icon_link(
  icon = "mastodon",
  text = "#rstats",
  url = "https://fosstodon.org/tags/rstats"
)`

## Data Science by Design

(h/t) Ella Kaye for informing me of this.

In her words, 

::: {.callout-note}
Data Science by Design (DSxD) celebrates creativity in data science and developing a more open, ethical, and inclusive future for data work. They run small conferences and an active slack group. They publish anthologies, both in print and online, collections of work by data designers, scientists, and artists, with each issue on a different theme.

Link: [The site I borrowed the description from.](https://ellakaye.co.uk/community.html)
:::

`r icon_link(
  icon = "globe",
  text = "website",
  url = "http://datasciencebydesign.org"
)`

`r icon_link(
  icon = "twitter",
  text = "Twitter",
  url = "https://twitter.com/DataScixDesign"
)`

`r icon_link(
  icon = "book",
  text = "book",
  url = "http://datasciencebydesign.org/book" 
)`